docs: Translate svelte 01-02 getting stated doc to Japanese
svelte-jp/svelte.dev pull request #10
Opened 2024-11-19 13:16 UTC by yuki0418

### A note on documentation PRs

If this is a documentation PR (i.e. changing content within `apps/svelte.dev/content/docs`), then this is the wrong repository to make those changes. The content in this folder is synced from other repositories. Therefore, these changes should be made in their respective repositories (at https://github.com/sveltejs/svelte or https://github.com/sveltejs/kit, or example).

こちらはテンプレートです。一旦そのままにしております。

## Issue
#9 

### Before submitting the PR, please make sure you do the following

- [x] It's really useful if your PR references an issue where it is discussed ahead of time.
- [x] Prefix your PR title with `feat:`, `fix:`, `chore:`, or `docs:`.
- [x] This message body should clearly illustrate what problems it solves.

2024-11-19 13:17 UTC, yuki0418 commented on apps/svelte.dev/content/docs/svelte/01-introduction/02-getting-started.md
>  title: Getting started
`Getting started` は next.js を見た時に日本語でも `Getting Started` だったのでそのままにしております。

2024-11-21 10:05 UTC, tomoam requested changes
早速のコントリビュートありがとうございます、助かります！

いくつか修正していただきたいところがございます。
（ほとんどはコントリビュートガイドの未整備に起因するものです、申し訳ありません）
コメントしましたので修正していただけますでしょうか。

2024-11-21 10:05 UTC, tomoam commented on apps/svelte.dev/content/docs/svelte/01-introduction/02-getting-started.md
> +## SvelteKit の代替手段
Svelteのサイトは見出しのアンカーを作成するのに見出しの文を使用しており、CJK圏のようなマルチバイト文字を使用すると見出しのアンカーが作成されなくなります。
そのため、日本語サイトでは以下のようにHTMLコメントを見出しの右に置くことで、アンカーを生成することができるようにしました。

https://github.com/svelte-jp/svelte.dev/blob/11322d51612d031ed0dc43294d907fac564613b1/apps/svelte.dev/content/docs/kit/10-getting-started/10-introduction.md?plain=1#L5

以下のように修正していただけますか。

```md
## SvelteKit の代替手段 <!--Alternatives-to-SvelteKit-->
```

2024-11-21 10:05 UTC, tomoam commented on apps/svelte.dev/content/docs/svelte/01-introduction/02-getting-started.md
> +## エディタツール
上記と同様です。
以下のように修正していただけますか。

```md
## エディタツール <!--Editor-tooling-->
```

2024-11-21 10:05 UTC, tomoam commented on apps/svelte.dev/content/docs/svelte/01-introduction/02-getting-started.md
> +## サポートを受ける
上記と同様です。
以下のように修正していただけますか。

```md
## サポートを受ける <!--Getting-help-->
```

2024-11-21 22:45 UTC, yuki0418 commented
@tomoam 
レビューありがとうございます！
修正完了したので再度レビューお願いいたします！

2024-11-27 09:18 UTC, tomoam approved these changes
お待たせしてしまい申し訳ありません。
ご対応ありがとうございます、マージさせていただきます！

2024-11-27 09:19 UTC, merged