Translate 03-svelte-files.md from en to jp
svelte-jp/svelte.dev pull request #13
Opened 2024-12-05 00:01 UTC by yuki0418

close #11 

### A note on documentation PRs

If this is a documentation PR (i.e. changing content within `apps/svelte.dev/content/docs`), then this is the wrong repository to make those changes. The content in this folder is synced from other repositories. Therefore, these changes should be made in their respective repositories (at https://github.com/sveltejs/svelte or https://github.com/sveltejs/kit, or example).

こちらはテンプレートです。一旦そのままにしております。

### Before submitting the PR, please make sure you do the following

- [x] It's really useful if your PR references an issue where it is discussed ahead of time.
- [x] Prefix your PR title with `feat:`, `fix:`, `chore:`, or `docs:`.
- [x] This message body should clearly illustrate what problems it solves.

2024-12-05 00:02 UTC, yuki0418 commented on apps/svelte.dev/content/docs/svelte/01-introduction/03-svelte-files.md
> +title: .svelte ファイル
.svelte files か .svelte ファイル かで迷いましたが後者にしました。
.svelte files の方が良さそうであれば教えてください

2024-12-05 00:03 UTC, yuki0418 commented on apps/svelte.dev/content/docs/svelte/01-introduction/03-svelte-files.md
> +コンポーネントは Svelte アプリケーションの構成要素です。これらは `.svelte` ファイルに書かれ、HTML のスーパーセットを使って記述されます。
適切なスーパーセットの訳が思いつかなかったのでカタカナにしてます。

2024-12-05 00:04 UTC, yuki0418 commented on apps/svelte.dev/content/docs/svelte/01-introduction/03-svelte-files.md
> +<!-- マークアップ (0行以上) はここに書きます -->
`zero or more items` が行を示してるのかと思い日本語では行と訳してます

2024-12-05 00:05 UTC, yuki0418 commented on apps/svelte.dev/content/docs/svelte/01-introduction/03-svelte-files.md
>  ## `<script>`
英字のままの場合は `## 始める前に <!--Before-we-begin-->` のような見出しアンカーにする必要はないと認識してますが、間違ってたら教えてください。

2024-12-05 00:10 UTC, yuki0418 commented
@tomoam 
1ファイル翻訳しました。
関係のないところで Lint error が発生しており CI が失敗しております。
一旦このまま PR 提出いたします。

レビューお願いします。

2025-01-14 09:45 UTC, tomoam requested changes
本当に長らくおまたせしました。
翻訳ありがとうございます。
2点のみ、対応していただけますでしょうか。

2025-01-14 09:45 UTC, tomoam commented on apps/svelte.dev/content/docs/svelte/01-introduction/03-svelte-files.md
ここは削除のし忘れかもしれません。

2025-01-14 09:45 UTC, tomoam commented on apps/svelte.dev/content/docs/svelte/01-introduction/03-svelte-files.md
ここも削除のし忘れかもしれません。

2025-01-14 11:53 UTC, yuki0418 commented on apps/svelte.dev/content/docs/svelte/01-introduction/03-svelte-files.md
ありがとうございます。
見落としておりました。
削除済みです。

2025-01-14 11:53 UTC, yuki0418 commented on apps/svelte.dev/content/docs/svelte/01-introduction/03-svelte-files.md
ありがとうございます。
見落としておりました。
削除済みです。

2025-01-14 11:54 UTC, yuki0418 commented
@tomoam 
レビューありがとうございます！
指摘箇所修正完了しました。

再レビューお願いいたします。

2025-01-14 23:18 UTC, tomoam approved these changes
ご対応ありがとうございました！
マージさせていただきます！

2025-01-14 23:18 UTC, merged